[[row]]
    ratio=2
    [[row.child]]
      type="temp"
    [[row.child]]
      ratio=2
      [[row.child.child]]
        type="proc"
      [[row.child.child]]
        type="cpu"
[[row]]
  [[row.child]]
  ratio=3
  type="mem"
  [[row.child]]
  ratio=2
  type="net"

[flags]
mem_as_value = true
color = "gruvbox"

#[disk_filter]
#is_list_ignored = true
#list = ["/dev/sda\\d+", "/dev/nvme0n1p2"]
#regex = true
#case_sensitive = false
#whole_word = false

#[mount_filter]
#is_list_ignored = true
#list = ["/mnt/.*", "/boot"]
#regex = true
#case_sensitive = false
#whole_word = false

#[temp_filter]
#is_list_ignored = true
#list = ["cpu", "wifi"]
#regex = false
#case_sensitive = false
#whole_word = false

#[net_filter]
#is_list_ignored = true
#list = ["virbr0.*"]
#regex = true
#case_sensitive = false
#whole_word = false
